spring:
  application:
    name: service-notification
  cloud:
    config:
      uri: http://localhost:8888/config
      fail-fast: false
  config:
    import: configserver:http://localhost:8888/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: false
    hostname: Localhost