spring:
  application:
    name: service-one
  cloud:
    config:
      uri: http://localhost:8888/config
  config:
    import: configserver:http://localhost:8888/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/